import Layout from 'components/layout';
import React from 'react';
import styles from 'styles/general.module.css';

const privacyTerms = () => (
  <Layout>
    <h1 className={`${styles.h1}`}>Terms of Use</h1>
    <p className={`${styles.p}`}>This page describes the general conditions and mutual responsibilities that all users must agree with, before using this site, or reusing their content.</p>
    <p className={`${styles.p}`}>These Terms of Use ("Terms") govern your use of this website hosted and provided by Kat England Tattoo, Inc. ("Kat England Tattoo", "us" or "we"), ("Website") and any services offered through the Website ("Services").</p>
    <p className={`${styles.p}`}>These Terms are a legal contract between you and us so it is important that you review them carefully.</p>
    <p className={`${styles.p}`}>For clarity, these Terms only apply to this Website and do not apply to any: use of open source code, documentation or specifications made available on GitHub, which are governed by the terms of the applicable open source license.</p>
    <p className={`${styles.p}`}>We may change these Terms or modify any features of the Website or the Services at any time. Any such change or modification will be effective immediately upon posting on our Website. You accept these Terms by browsing this Website and/or using the Services, and you accept any changes to the Terms by continuing to use the Website after we post any such changes.</p>
    <p className={`${styles.p}`}>If you do not agree to these Terms, please do not access or use the Website.</p>
    <p className={`${styles.p}`}>If you need to contact us for any reason, please do so at tattsbykat@gmail.com</p>
    <h2 className={`${styles.h2}`}>1. What you can do on this Website</h2>
    <p className={`${styles.p}`}>We make this Website available to you and others to help everyone understand our services. In exchange, we need you to make the following commitments:</p>
    <p className={`${styles.p}`}>(a) Who can use the Website</p>
    <p className={`${styles.p}`}>We try to make our Website broadly available to everyone, but you cannot use our Website if:</p>
    <p className={`${styles.p}`}> • You are a minor in your country of residence except if your parents or guardians have agreed to these Terms on your behalf.</p>
    <p className={`${styles.p}`}> • You are prohibited from accessing the Website under applicable laws.</p>
    <p className={`${styles.p}`}>(b) What you can share and do on the Website</p>
    <p className={`${styles.p}`}>You agree not to engage in the conduct described below (or to facilitate or support others in doing so):</p>
    <p className={`${styles.p}`}> 1. You may not use our Website, do or share anything:</p>
    <p className={`${styles.p}`}> ◦ That violates these Terms (and other terms and policies that apply to your use of the Website);</p>
    <p className={`${styles.p}`}> ◦ That is unlawful in any country, misleading, discriminatory or fraudulent; and/or</p>
    <p className={`${styles.p}`}> ◦ That infringes or violates someone else's rights, including their intellectual property rights.</p>
    <p className={`${styles.p}`}> 2. You may not upload viruses or malicious code or do anything that could disable, overburden, or impair the proper working or appearance of the Services or Website.</p>
    <p className={`${styles.p}`}>(c) Access to the Website</p>
    <p className={`${styles.p}`}>The Website is made available free of charge and the Services are available only for informational purposes. We make no representations or warranties of any kind as to the accuracy, currency, or completeness of the information and other materials made available through the Website and are not liable for any decisions you may make in reliance on this content.</p>
    <h2 className={`${styles.h2}`}>2. Links To Third-Party Content</h2>
    <p className={`${styles.p}`}>The Website or Services may contain links to third-party content. For example, our user communities may be hosted by third party platforms over which we have no control and for which we have no responsibility. Therefore, please review each of these platforms or websites' terms of use and privacy policies before participating.</p>
    <p className={`${styles.p}`}>We do not control, endorse, sponsor, recommend, or otherwise accept responsibility for any content, terms of use, policies on or use of any third party website.</p>
    <h2 className={`${styles.h2}`}>3. Limits on liability</h2>
    <p className={`${styles.p}`}>We work hard to provide the best Website and Services we can and to specify clear guidelines for everyone who uses them. Our Website and Services, however, are provided "as is," and we make no guarantees that they always will be safe, secure, or error-free, that they will function without disruptions, delays, or imperfections or that the content will be accurate, current and complete. To the extent permitted by law, we also DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT IN RELATION TO THE WEBSITE, THE SERVICES AND THEIR CONTENT. We do not control or direct what people and others do or say, and we are not responsible for their actions or conduct (whether online or offline) or any content they share (including offensive, inappropriate, obscene, unlawful, and other objectionable content). Some jurisdictions do not allow the exclusion or limitation of implied warranties, in which case parts of this disclaimer may not apply to you.</p>
    <p className={`${styles.p}`}>We cannot predict when issues might arise with our Website and Services. Accordingly, our liability shall be limited to the fullest extent permitted by applicable law, and under no circumstance will we be liable to you for any lost profits, revenues, information, or data, or consequential, special, indirect, exemplary, punitive, or incidental damages arising out of or related to these Terms, the Website or the Services, even if we have been advised of the possibility of such damages. Our aggregate liability arising out of or relating to these Terms, the Website or the Services will not exceed $100.</p>
    <p className={`${styles.p}`}>We do not exclude or limit in any way our liability to you where it would be unlawful to do so therefore depending on the country where you reside some of these exclusions and limitations may not apply to you.</p>
    <h2 className={`${styles.h2}`}>4. Disputes</h2>
    <p className={`${styles.p}`}>We try to provide clear rules so that we can limit or hopefully avoid disputes between you and us. If a dispute does arise, however, it's useful to know up front where it can be resolved and what laws will apply.</p>
    <p className={`${styles.p}`}>For any claim, cause of action, or dispute you have against us that arises out of or relates to these Terms, the Website and/or the Services ("claim"), you agree that it will be resolved exclusively in the U.S. District Court for the Eastern District of Tennessee or a state court located in Knox County. You also agree to submit to the personal jurisdiction of either of these courts for the purpose of litigating any such claim, and that the laws of the State of Tennessee will govern these Terms and any claim, without regard to conflict of law provisions.</p>
    <p className={`${styles.p}`}>The preceding provision regarding applicable law and venue does not apply if you are a consumer based in the European Union. If you are a consumer based in the European Union, these Terms will be subject to the laws of your country of residence and you may bring a claim in front of those courts.</p>
    <h2 className={`${styles.h2}`}>5. Privacy</h2>
    <p className={`${styles.p}`}>Under data protection legislation, we are required to provide you with certain information about who we are, how we process your personal data and for what purposes and your rights in relation to your personal data and how to exercise them. This information is provided in Privacy Policy (below) and it is important that you read that information.</p>
    <h2 className={`${styles.h2}`}>6. Other important terms</h2>
    <p className={`${styles.p}`}>These Terms make up the entire agreement between you and Kat England Tattoo, Inc. regarding your use of our Services and this Website. They supersede any prior agreements.</p>
    <p className={`${styles.p}`}>If any portion of these Terms is found to be unenforceable, the remaining portion will remain in full force and effect. If we fail to enforce any of these Terms, it will not be considered a waiver. Any amendment to or waiver of these Terms must be made in writing and signed by us.</p>
    <p className={`${styles.p}`}>You will not transfer any of your rights or obligations under these Terms to anyone else without our consent.</p>
    <p className={`${styles.p}`}>You agree that no joint venture, partnership, employment, or agency relationship exists between you and us as a result of these Terms or your access to and use of the Website or Services.</p>
    <p className={`${styles.p}`}>These Terms do not confer any third-party beneficiary rights. All of our rights and obligations under these Terms are freely assignable by us in connection with a merger, acquisition, or sale of assets, or by operation of law or otherwise.</p>
    <p className={`${styles.p}`}>We reserve all rights not expressly granted to you.</p>

    <h1 className={`${styles.h1}`}>Privacy Policy</h1>
    <p className={`${styles.p}`}>This policy describes our practices for handling your information on this website (the "Services").</p>
    <h2 className={`${styles.h2}`}>Collection of Information</h2>
    <p className={`${styles.p}`}>When you interact with us through our Services, we may collect or receive the following types of information:</p>
    <p className={`${styles.p}`}>Information you provide directly to us. For certain activities, we may collect the following types of information:</p>
    <p className={`${styles.p}`}> • Contact information, such as name and email address; and</p>
    <p className={`${styles.p}`}> • Information you provide us when you send us correspondence, reserve to a service, or otherwise participate on the Services.</p>
    <p className={`${styles.p}`}>Information we collect automatically. We may also collect certain information automatically when you use our Services, such as your Internet protocol (IP) address, mobile device identifier, browser type, operating system, Internet service provider, pages that you visit before and after using the Services, the date and time of your visit, information about the links you click and pages you view within the Services, and other standard server log information.</p>
    <p className={`${styles.p}`}>Integrations with Other Services. Our Services refer to Other various online services, such as Facebook, Twitter or Youtube (collectively, "platforms"). Our Services may enable you to access these platforms indirectly through our Services. By including these platforms, we aim to make your online experiences richer and more personalized. Refer to these Other Services' Privacy Policies for how they handle your data.</p>
    <p className={`${styles.p}`}>As part of an integration with a platform, that platform may provide us with access to certain information that you have provided to the platform, and we will use, store, and disclose such information in accordance with this Privacy Policy. However, please remember that the manner in which platforms use, store, and disclose your information is governed by the policies that apply to those platforms.</p>
    <p className={`${styles.p}`}>Information we obtain from other sources. It is possible that we may receive information about you from other sources, including through third-party services and organizations, which we may combine with other information we receive about you.</p>
    <p className={`${styles.p}`}>We attempt to collect the minimal personal information possible to deliver our services to you.</p>
    <h2 className={`${styles.h2}`}>How We Use Information</h2>
    <p className={`${styles.p}`}>We may use the information you provide us to:</p>
    <p className={`${styles.p}`}> • Meet our legitimate interests, including to fulfill your requests for resources, services, and information; analyze the use of the Services and user data to understand, improve and operate the Services; and customize the content you see when you use the Services;</p>
    <p className={`${styles.p}`}> • Meet our legal obligations, including to prevent potentially prohibited or illegal activities and otherwise in accordance with our Terms of Use and comply with legal requirements; and</p>
    <p className={`${styles.p}`}> • For any other purposes disclosed to you at the time we collect your information or pursuant to your consent.</p>
    <p className={`${styles.p}`}>The primary use of any information you provide to Us is to deliver our services to you.</p>
    <h2 className={`${styles.h2}`}>How We Share Information</h2>
    <p className={`${styles.p}`}>There are certain circumstances in which we may share your information with certain third parties without further notice to you, as set forth below:</p>
    <p className={`${styles.p}`}> • Authorized third-party vendors and service providers. We share your information with third-party vendors and service providers that help us with specialized services, including email deployment, business analytics, marketing, and data processing. These services providers are limited from using your information for any purpose other than to perform services for us.</p>
    <p className={`${styles.p}`}> • Affiliates. We may share your information with our affiliates, which are companies that control, are controlled by, or are under common control with us.</p>
    <p className={`${styles.p}`}> • Legal purposes. We may disclose information to respond to subpoenas, court orders, legal process, law enforcement requests, legal claims or government inquiries, detect fraud, and to protect and defend the rights, interests, safety, and security of Kat England Tattoo, our affiliates, owner, users, or the public.</p>
    <p className={`${styles.p}`}> • Business transfers. We may share your information in connection with a substantial corporate transaction, such as the sale of a website, a merger, consolidation, asset sale, or in the unlikely event of bankruptcy.</p>
    <p className={`${styles.p}`}> • With your consent. We may share information for any other purposes disclosed to you at the time we collect the information or pursuant to your consent. If you choose to engage in public activities on the website, you should be aware that any information you share there can be read, collected, or used by other users of these areas. You should use caution in disclosing personal information while participating in these areas. We are not responsible for the information you choose to submit in these public areas.</p>
    <p className={`${styles.p}`}>How We Protect Information We take measures to help protect information from loss, theft, misuse and unauthorized access, disclosure, alteration, and destruction. However, no data storage system or transmission of data over the Internet or any other public network can be guaranteed to be 100 percent secure.</p>
    <p className={`${styles.p}`}>Please note that information collected by third parties may not have the same security protections as information you submit to us, and we are not responsible for protecting the security of such information.</p>
    <h2 className={`${styles.h2}`}>Your California Privacy Rights</h2>
    <p className={`${styles.p}`}>We do not share personal information with third parties for their own direct marketing purposes.</p>
    <p className={`${styles.p}`}>Do-Not-Track Signals and Similar Mechanisms. Some web browsers transmit "do-not-track" signals to websites. Because of differences in how web browsers incorporate and activate this feature, it is not always clear whether users intend for these signals to be transmitted, or whether they even are aware of them. We currently do not take action in response to these signals.</p>
    <h2 className={`${styles.h2}`}>Children’s Information</h2>
    <p className={`${styles.p}`}>Kat England Tattoo does not knowingly collect or store information from children under the age of 13, unless permitted by law. We will delete any information we may have inadvertently received from a child under 13 upon notice. If you have reason to believe that a child under the age of 13 has provided personal information to Kat England Tattoo through our Services please contact us and we will endeavor to delete that information from our databases.</p>
    <h2 className={`${styles.h2}`}>Cookies</h2>
    <p className={`${styles.p}`}>We may use cookies, pixel tags, and similar technologies to automatically collect this information. Cookies are small bits of information that are stored by your computer’s web browser. Pixel tags are very small images or small pieces of data embedded in images, also known as "web beacons" or "clear GIFs," that can recognize cookies, the time and date a page is viewed, a description of the page where the pixel tag is placed, and similar information from your computer or device. By using the Services, you consent to our use of cookies and similar technologies. You may be able to refuse or disable cookies by adjusting your web browser settings. Because each web browser is different, please consult the instructions provided by your web browser (typically in the "help" section). </p>
    <h2 className={`${styles.h2}`}>Changes to this Policy</h2>
    <p className={`${styles.p}`}>We may update or modify this Privacy Policy at any time without prior notice. When we update the Privacy Policy, we will revise the "Effective Date" date below and post the new Privacy Policy. We recommend that you review the Privacy Policy each time you visit the Services to stay informed of our privacy practices. Any changes will be effective when we post the revised policy. Your continued use of our Services after any changes or revisions to this Privacy Policy shall indicate your agreement with the terms of such revised Privacy Policy.</p>
    <h2 className={`${styles.h2}`}>Questions</h2>
    <p className={`${styles.p}`}>If you have any questions about this Privacy Policy or our practices, please contact us at tattsbykat@gmail.com.</p>
    <p className={`${styles.p}`}>Effective Date: 2021-01-09</p>
  </Layout>
);

export default privacyTerms;
